global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'eureka-server'
    static_configs:
      - targets: ['localhost:8761']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8001']

  - job_name: 'hospital-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8002']

  - job_name: 'doctor-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8003']

  - job_name: 'reservation-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8009']

  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8010']


